### ISSUE TITLE
Readme.md file misspelled

### ISSUE THREAD

**Issue by wnflrj123** [majidgolshadi/Android-Download-Manager-Pro#10]
Plz look at line 59~!

Initialize DownloadManagerPro

`String saveFielPath`: folder address that you want to save your completed download task in it.

I think that you need to modify the "saveFielPath" to "saveFilePath".
So I think it should be modified in the following sentence.

`String saveFilePath`: folder address that you want to save your completed download task in it.

Thank you :D ~

**Comment by KimTaehee** [comment]
I think that was misspelled too.

**Comment by majidgolshadi** [comment]
Thank you @wnflrj123 
That was a misspelled in documentation
