### ISSUE TITLE
Not downloading video file

### ISSUE THREAD

**Issue by danielto** [majidgolshadi/Android-Download-Manager-Pro#13]
Hello,

when I try to download some video files, it does nothing.  OnDownloadStarted is called, but nothing else.

The file that I try to download is: http://www.sample-videos.com/video/mp4/360/big_buck_bunny_360p_2mb.mp4 

This is what I get from downloadTasksInSameState:

```
{
  "token":"39",
  "name":"save_name_15",
  "state":3,
  "resumable":true,
  "fileSize":-1,
  "url":"http:\/\/www.sample-videos.com\/video\/mp4\/360\/big_buck_bunny_360p_2mb.mp4",
  "type":"mp4",
  "chunks":1,
  "percent":0,
  "downloadLength":0,
  "saveAddress":"\/storage\/emulated\/0\/downloadManager\/save_name_15.mp4",
  "priority":true
}
```

Thank you for your help.

Daniel

**Comment by majidgolshadi** [comment]
As you can see library can't get the file size.
This server doesn't provide enough information to the library(As i checked), so it does have to idea how to split the file to chunks.

**Comment by danielto** [comment]
Thank you for your answer.

Have a nice day.
