### ISSUE TITLE
Unable to download files 

### ISSUE THREAD

**Issue by taimur97** [majidgolshadi/Android-Download-Manager-Pro#15]
Hi, 
Just tried this library and I am not able to download files. I tried downloading from these sites apkleecher.com and www.mp3juices.cc. 
It says Download started but the download is never completed and I see small files created in external storage. 
Can you please verify it if it is an issue with the library or with the sites?

**Comment by taimur97** [comment]
And why I have to specify filename. It should fetch the filename from the link

**Comment by majidgolshadi** [comment]
This lib can only download files with direct links that file serve server return file information in response header on library request to download that.
I can't find these features on this server.

**Comment by hrdabhi** [comment]
Please add feature to get download file from redirected URL.
This will help you to get actual URL.

`/**
     * Http HEAD Method to get actual URL
     *
     * @param urlString urlString
     * @return redirected URL
     * @throws IOException
     */
    private static String getActualUrl(String urlString) throws IOException {
        URL url = new URL(urlString);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setRequestProperty("Accept-Encoding", "");
        connection.setRequestMethod("HEAD");
        if (isRedirect(connection.getResponseCode())) {
            String newUrl = connection.getHeaderField("Location");
            System.out.println("newUrl: "+newUrl);
            return newUrl;
        }
        return urlString;
    }

    /**
     * Check status code for redirects
     *
     * @param statusCode true
     * @return true if matched redirect group
     */
    private static boolean isRedirect(int statusCode) {
        if (statusCode != HttpURLConnection.HTTP_OK) {
            if (statusCode == HttpURLConnection.HTTP_MOVED_TEMP
                    || statusCode == HttpURLConnection.HTTP_MOVED_PERM
                    || statusCode == HttpURLConnection.HTTP_SEE_OTHER) {
                return true;
            }
        }
        return false;
    }`

**Comment by xeeoon** [comment]
@hrdabhi 
Thank you for that, it works!
