### ISSUE TITLE
pause all downloads and dispose

### ISSUE THREAD

**Issue by danielto** [majidgolshadi/Android-Download-Manager-Pro#16]
Hello,

do I need to worry about downloading states when I call dispose()?

I run the downloadManagerPro in the service. But the service can be stopped by the system. So in the onDestroy I want to pause all downloading files and then call dispose. But there is no listener for onPauseAllDownloads. 

So my question is: Do I need to pause dowloads before dispose or can I omit the dispose function at all?

Thank you in advance.

**Comment by majidgolshadi** [comment]
No
`dispose()` method only disconnect your application from download manager db so no data corruption will be happening.
