### ISSUE TITLE
AsyncWorker exception

### ISSUE THREAD

**Issue by ColdBrando** [majidgolshadi/Android-Download-Manager-Pro#21]
java.net.protocolException: unexpected end of stream 
AsyncWorker.run (AsyncWorker.java:65)

**Comment by fanOfDemo** [comment]
I have solved this problem.


This is my project,it work fine [YueWenGameDownloadDemo](https://github.com/fanOfDemo/YueWenGameDownloadDemo)


  *  [google code issues](https://code.google.com/p/android/issues/detail?id=160705)
           
  *  [okhttp issues](https://github.com/square/okhttp/issues/1490)

Thinks to majidgolshadi's [Android-Download-Manager-Pro](https://github.com/majidgolshadi/Android-Download-Manager-Pro)
