### ISSUE TITLE
Question of queue download

### ISSUE THREAD

**Issue by QiuDaniel** [majidgolshadi/Android-Download-Manager-Pro#22]
I want to start a queue with 5 download tasks, what should I do from the start to the end?

**Comment by majidgolshadi** [comment]
Every task store in db and return you a token by `addTask`.
You can sort added tasks and start download based on those priority by using `StartQueueDownload(int downloadTaskPerTime, int sortType)` method.
- QueueSort.**HighPriority** : only high priority
- QueueSort.**LowPriority** : only low priority
- QueueSort.**HighToLowPriority** : sort queue from high to low priority
- QueueSort.**LowToHighPriority** : sort queue from low to high priority
- QueueSort.**earlierFirst** : sort queue from earlier to oldest tasks
- QueueSort.**oldestFirst** : sort queue from old to earlier tasks
