### ISSUE TITLE
Download mode from where it stopped

### ISSUE THREAD

**Issue by zangchung** [majidgolshadi/Android-Download-Manager-Pro#3]
Thank you for opening this good module
But I guess that this module only support overwrite or not.
I can add function "download from where it stopped", if you want
I change value type 'boolean overwrite' to 'int downloadMode' in addTask() method.
int downloadMode can be tree types
1. overwrite
2. not overwrite
3. download from where it stopped(and sure I add relative code)
1,2 is same boolean overwrite.
Please check my opinion.

**Comment by majidgolshadi** [comment]
Hi zangchung

I can't find-out what you really want to say but if i understand correctly, you want to add a new state to system but i think this state is not really necessary.
Any download task can be start from when ever task failed or paused with only call `start()` method.

Thank you for your feedback.

**Comment by zangchung** [comment]
OK I see. I understand this download task can be start from when ever failed or paused
Thank you for your detailed explanation.
