### ISSUE TITLE
How to add it to my project?

### ISSUE THREAD

**Issue by elmondogri** [majidgolshadi/Android-Download-Manager-Pro#32]
Hello, I am kind of confused and also new to java, but usualy libraryz have some kind of tutorial like:

"download this jar and put it in the folder xxx"
Or
"Add dependencie xxxx to gradle"

But on this one I can t find anything and it s frustrating as I would like to use this library on my project.

Can someone please give me the steps to use it? Thank you

**Comment by majidgolshadi** [comment]
To add it as a library to your project with package manager read these steps [http://android-arsenal.com/details/1/2131#package](http://android-arsenal.com/details/1/2131#package)
**OR**
Use it as a part of your code (Copy/Past). ;)
