### ISSUE TITLE
Cursor object not always closed properly

### ISSUE THREAD

**Issue by zunjae** [majidgolshadi/Android-Download-Manager-Pro#36]
for example you forgot to close it in `TaskDataSource` in the method `getUnCompletedTasks`

You are also not persistent in the way you close your cursors. Sometimes you check if the cursor object is `null`, and sometimes you do not.

Is there also a reason why the connection to the database is never closed? I see an unused method called close() in TaskDataSource. I do not properly understand the source code just yet to understand when I should call this method

**Comment by majidgolshadi** [comment]
Thank you for your feedback.
I create a pull request #40 .
@zunjae Would you please see and feedback
