### ISSUE TITLE
unexpected end of stream error for large files

### ISSUE THREAD

**Issue by ajmalrasi** [majidgolshadi/Android-Download-Manager-Pro#47]
Getting this error while download large files, size larger than 20MB

`ajmalrasi.com.rasi.hellod W/System.err: java.net.ProtocolException: unexpected end of stream
ajmalrasi.com.rasi.hellod W/System.err:     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:421)
ajmalrasi.com.rasi.hellod W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
ajmalrasi.com.rasi.hellod W/System.err:     at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
ajmalrasi.com.rasi.hellod W/System.err:     at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
ajmalrasi.com.rasi.hellod W/System.err:     at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
ajmalrasi.com.rasi.hellod W/System.err:     at java.io.FilterInputStream.read(FilterInputStream.java:107)
ajmalrasi.com.rasi.hellod W/System.err:     at com.golshadi.majid.core.chunkWorker.AsyncWorker.run(AsyncWorker.java:94)`

any idea how to solve this issue, looked up this error on google but couldn't a find solution.

**Comment by kyze8439690** [comment]
I have meet this issue before, and it is a CDN server issue, maybe you should check of this.

**Comment by ajmalrasi** [comment]
You are right, the issue was with the server.
