### ISSUE TITLE
ادامه دادن دانلود 

### ISSUE THREAD

**Issue by sinadalvand** [majidgolshadi/Android-Download-Manager-Pro#52]
با سلام و عرض خسته نباشید

من میخواستم از این کتابخونه استفاده کنم اما قبلش نیازه این سوال رو بپرسم 

مثلا من یک فایل رو دادم دانلود کنه و اون فایل تا نصفه دانلود شده ، حالا من برنامه رو میبندم و میخوام وقتی کاربر بعدا دوباره وارد برنامه شد و ادامه دانلود رو زد ، دادمه فایل دانلود بشه ایا همچین چیزی توی این کتابخونه هست؟

با تشکر

**Comment by majidgolshadi** [comment]
Please translate your question to english

**Comment by sinadalvand** [comment]
Excuse me for asking my question in Persian language ; i think your name & family is like as Iranian people for this reason i used FA

 my question was about resume download , after searching in another issue i found my answer

thanks
