### ISSUE TITLE
onDownloadFinished & onDownloadCompleted

### ISSUE THREAD

**Issue by RandallXia** [majidgolshadi/Android-Download-Manager-Pro#55]
Hi~Can you explain this difference between those two interfaces?

**Comment by majidgolshadi** [comment]
As you can see here ![graph](https://github.com/majidgolshadi/Android-Download-Manager-Pro/blob/master/docs/images/states.jpg) (the graph on top of documentation) after download all partyou notify in `ondownloadFinished` method and when all part attach to eachother and make a single file service goes to `onDownloadComplete` state and you can notify in.
