### ISSUE TITLE
How to know in which state downloader now ?

### ISSUE THREAD

**Issue by kirill-kostenetskyi** [majidgolshadi/Android-Download-Manager-Pro#8]
Please, help me to understandm how can i know in which state my task : pause, downlaoded or something else. After i write ReportStructure report = dm.singleDownloadStatus(taskToken); how can i get information from that ? Thank you

**Comment by majidgolshadi** [comment]
Hi
In singleDownloadStatus method you got a ReportStructure object that contain state property. As I mention in readme you can find your task state
- TaskState.INIT: task intruduce for library and gave you token back but it didn't started yet.
- TaskState.READY: download task data fetch from its URL and it's ready to start.
- TaskState.DOWNLOADING: download task in downloading process.
- TaskState.PAUSED: download task in puase state. If in middle of downloading process internet disconnected; task goes to puase state and you can start it later
- TaskState.DOWNLOAD_FINISHED: download task downloaded completely but their chunks did not rebuild.
- TaskState.END: after rebuild download task chunks, task goes to this state and notified developer with OnDownloadCompleted(long taskToken) interface

**Comment by kirill-kostenetskyi** [comment]
i found how to get states. i added getState method to ReportStructure class , and when i need to current state of downlaod, i just call it.
thank you
